services:
  app1:
    image: 1234a4321/app1:1.1
    working_dir: /app
    volumes:
      - /home/kiriakos/Documents/vs_code/firmwares/app1:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=6379
      - REDIS_DB=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_API_VERSION=1.41
    privileged: true
    restart: unless-stopped
    networks:
      - app_network
networks:
  app_network:
    driver: bridge